###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            hanwckf | https://github.com/hanwckf             #
###############################################################

name: Build Padavan

on:
  push:
    paths:
      - 'triggers/build-padavan-ng.md'

env:
  REPO_URL: https://github.com/vietanhbui2000/padavan-ng
  REPO_BRANCH: update
  DEVICE_NAME: MiWiFi-R1CM
  CUSTOMIZE_FIRMWARE: false
  USE_PRECOMPILED_TOOLCHAIN: true
  CUSTOMIZE_SH: scripts/padavan/customize.sh
  DL_TOOLCHAIN_SH: scripts/padavan/dl_toolchain_ng.sh
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install git build-essential gawk pkg-config gettext automake autoconf autopoint libtool bison flex zlib1g-dev libgmp3-dev libmpfr-dev libmpc-dev texinfo mc libncurses5-dev nano vim autopoint gperf python-docutils help2man libtool-bin libtool-doc
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        git clone $REPO_URL opt/padavan-ng
        cd opt/padavan-ng
        git checkout $REPO_BRANCH

    - name: Load device configuration
      run: |
        cp -R configs/padavan-ng/$DEVICE_NAME opt/padavan-ng/trunk/configs/boards/XIAOMI
        cp configs/padavan-ng/$DEVICE_NAME.config opt/padavan-ng/trunk/.config
        cp configs/padavan-ng/$DEVICE_NAME.config opt/padavan-ng/trunk/configs/templates/xiaomi/$DEVICE_NAME.config

    - name: Customize firmware
      if: env.CUSTOMIZE_FIRMWARE == 'true' && !cancelled()
      run: |
        cp $CUSTOMIZE_SH opt/padavan-ng/trunk/customize.sh
        cd opt/padavan-ng/trunk
        chmod +x customize.sh
        ./customize.sh

    - name: Download pre-compiled toolchain
      if: env.USE_PRECOMPILED_TOOLCHAIN == 'true' && !cancelled()
      run: |
        cp $DL_TOOLCHAIN_SH opt/padavan-ng/toolchain/dl_toolchain.sh
        cd opt/padavan-ng/toolchain
        sh dl_toolchain.sh

    - name: Compile toolchain
      if: env.USE_PRECOMPILED_TOOLCHAIN == 'false' && !cancelled()
      run: |
        cd opt/padavan-ng/toolchain
        ./clean_sources.sh
        ./build_toolchain.sh

    - name: Clean up files
      run: |
        cd opt/padavan-ng/trunk
        ./clear_tree.sh

    - name: Compile firmware
      id: compile
      run: |
        cd opt/padavan-ng/trunk
        fakeroot ./build_firmware.sh
        echo "::set-output name=status::success"
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload firmware
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE_NAME }}_padavan-ng_${{ env.DATE }}
        path: opt/padavan-ng/trunk/images/*.trx
